# https://github.com/google/yamlfmt/blob/main/docs/config-file.md
formatter:
    type: basic
    include_document_start: false # Omit ---
    line_ending: lf
    max_line_length: 80
    indent: 4
    pad_line_comments: 1
    retain_line_breaks: false
    scan_folded_as_literal: false
